# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data Science Initiative
email: dsi foobar
description: > # this means to ignore newlines until "baseurl:"
  The Data Science Initiative at UCI is super cool.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ucidatascienceinitiative.github.io" # the base hostname & protocol for your site
facebook_username: uci.datascience
github_username:  UCIDataScienceInitiative

# Build settings
markdown: kramdown
